//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.17 at 02:12:00 PM CEST 
//


package com.philips.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.philips.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.philips.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Products }
     * 
     */
    public Products createProducts() {
        return new Products();
    }

    /**
     * Create an instance of {@link Products.Product }
     * 
     */
    public Products.Product createProductsProduct() {
        return new Products.Product();
    }

    /**
     * Create an instance of {@link Products.Product.CSItem }
     * 
     */
    public Products.Product.CSItem createProductsProductCSItem() {
        return new Products.Product.CSItem();
    }

    /**
     * Create an instance of {@link Products.Product.NamingString }
     * 
     */
    public Products.Product.NamingString createProductsProductNamingString() {
        return new Products.Product.NamingString();
    }

    /**
     * Create an instance of {@link Products.Product.Feature }
     * 
     */
    public Products.Product.Feature createProductsProductFeature() {
        return new Products.Product.Feature();
    }

    /**
     * Create an instance of {@link Products.Product.CSItem.CSValue }
     * 
     */
    public Products.Product.CSItem.CSValue createProductsProductCSItemCSValue() {
        return new Products.Product.CSItem.CSValue();
    }

    /**
     * Create an instance of {@link Products.Product.CSItem.UnitOfMeasure }
     * 
     */
    public Products.Product.CSItem.UnitOfMeasure createProductsProductCSItemUnitOfMeasure() {
        return new Products.Product.CSItem.UnitOfMeasure();
    }

    /**
     * Create an instance of {@link Products.Product.NamingString.Family }
     * 
     */
    public Products.Product.NamingString.Family createProductsProductNamingStringFamily() {
        return new Products.Product.NamingString.Family();
    }

    /**
     * Create an instance of {@link Products.Product.NamingString.Descriptor }
     * 
     */
    public Products.Product.NamingString.Descriptor createProductsProductNamingStringDescriptor() {
        return new Products.Product.NamingString.Descriptor();
    }

}
