//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.17 at 02:12:00 PM CEST 
//


package com.philips.jaxb;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Product">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CTN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DTN" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="NamingString">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Family">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="FamilyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Descriptor">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="DescriptorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Feature" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="FeatureCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="FeatureReferenceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="FeatureName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="FeatureLongDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="FeatureGlossary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="FeatureRank" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="FeatureTopRank" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="CSItem">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CSValue">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CSValueName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="UnitOfMeasure">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="UnitOfMeasureName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="UnitOfMeasureSymbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Country" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Locale" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="IsMaster" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="IsAccessory" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="masterLastModified" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="DocTimeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="DocStatus" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "product"
})
@XmlRootElement(name = "Products")
public class Products {

    @XmlElement(name = "Product", required = true)
    protected Products.Product product;
    @XmlAttribute(name = "DocTimeStamp")
    @XmlSchemaType(name = "dateTime")
    protected Date docTimeStamp;
    @XmlAttribute(name = "DocStatus")
    protected String docStatus;

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link Products.Product }
     *     
     */
    public Products.Product getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link Products.Product }
     *     
     */
    public void setProduct(Products.Product value) {
        this.product = value;
    }

    /**
     * Gets the value of the docTimeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getDocTimeStamp() {
        return docTimeStamp;
    }

    /**
     * Sets the value of the docTimeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setDocTimeStamp(Date value) {
        this.docTimeStamp = value;
    }

    /**
     * Gets the value of the docStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocStatus() {
        return docStatus;
    }

    /**
     * Sets the value of the docStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocStatus(String value) {
        this.docStatus = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CTN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DTN" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="NamingString">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Family">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="FamilyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Descriptor">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="DescriptorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Feature" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="FeatureCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="FeatureReferenceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="FeatureName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="FeatureLongDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="FeatureGlossary" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="FeatureRank" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="FeatureTopRank" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="CSItem">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CSValue">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CSValueName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="UnitOfMeasure">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="UnitOfMeasureName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="UnitOfMeasureSymbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="Country" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Locale" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="IsMaster" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="IsAccessory" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="masterLastModified" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ctn",
        "dtn",
        "namingString",
        "feature",
        "csItem"
    })
    public static class Product {

        @XmlElement(name = "CTN", required = true)
        protected String ctn;
        @XmlElement(name = "DTN")
        protected String dtn;
        @XmlElement(name = "NamingString", required = true)
        protected Products.Product.NamingString namingString;
        @XmlElement(name = "Feature")
        protected List<Products.Product.Feature> feature;
        @XmlElement(name = "CSItem", required = true)
        protected Products.Product.CSItem csItem;
        @XmlAttribute(name = "Country")
        protected String country;
        @XmlAttribute(name = "Locale")
        protected String locale;
        @XmlAttribute(name = "IsMaster")
        protected String isMaster;
        @XmlAttribute(name = "IsAccessory")
        protected String isAccessory;
        @XmlAttribute(name = "masterLastModified")
        @XmlSchemaType(name = "dateTime")
        protected Date masterLastModified;

        /**
         * Gets the value of the ctn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCTN() {
            return ctn;
        }

        /**
         * Sets the value of the ctn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCTN(String value) {
            this.ctn = value;
        }

        /**
         * Gets the value of the dtn property.
         * 
         */
        public String getDTN() {
            return dtn;
        }

        /**
         * Sets the value of the dtn property.
         * 
         */
        public void setDTN(String value) {
            this.dtn = value;
        }

        /**
         * Gets the value of the namingString property.
         * 
         * @return
         *     possible object is
         *     {@link Products.Product.NamingString }
         *     
         */
        public Products.Product.NamingString getNamingString() {
            return namingString;
        }

        /**
         * Sets the value of the namingString property.
         * 
         * @param value
         *     allowed object is
         *     {@link Products.Product.NamingString }
         *     
         */
        public void setNamingString(Products.Product.NamingString value) {
            this.namingString = value;
        }

        /**
         * Gets the value of the feature property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the feature property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFeature().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Products.Product.Feature }
         * 
         * 
         */
        public List<Products.Product.Feature> getFeature() {
            if (feature == null) {
                feature = new ArrayList<Products.Product.Feature>();
            }
            return this.feature;
        }

        /**
         * Gets the value of the csItem property.
         * 
         * @return
         *     possible object is
         *     {@link Products.Product.CSItem }
         *     
         */
        public Products.Product.CSItem getCSItem() {
            return csItem;
        }

        /**
         * Sets the value of the csItem property.
         * 
         * @param value
         *     allowed object is
         *     {@link Products.Product.CSItem }
         *     
         */
        public void setCSItem(Products.Product.CSItem value) {
            this.csItem = value;
        }

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountry(String value) {
            this.country = value;
        }

        /**
         * Gets the value of the locale property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocale() {
            return locale;
        }

        /**
         * Sets the value of the locale property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocale(String value) {
            this.locale = value;
        }

        /**
         * Gets the value of the isMaster property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsMaster() {
            return isMaster;
        }

        /**
         * Sets the value of the isMaster property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsMaster(String value) {
            this.isMaster = value;
        }

        /**
         * Gets the value of the isAccessory property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsAccessory() {
            return isAccessory;
        }

        /**
         * Sets the value of the isAccessory property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsAccessory(String value) {
            this.isAccessory = value;
        }

        /**
         * Gets the value of the masterLastModified property.
         * 
         * @return
         *     possible object is
         *     {@link Date }
         *     
         */
        public Date getMasterLastModified() {
            return masterLastModified;
        }

        /**
         * Sets the value of the masterLastModified property.
         * 
         * @param value
         *     allowed object is
         *     {@link Date }
         *     
         */
        public void setMasterLastModified(Date value) {
            this.masterLastModified = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CSValue">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CSValueName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="UnitOfMeasure">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="UnitOfMeasureName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="UnitOfMeasureSymbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "csValue",
            "unitOfMeasure"
        })
        public static class CSItem {

            @XmlElement(name = "CSValue", required = true)
            protected Products.Product.CSItem.CSValue csValue;
            @XmlElement(name = "UnitOfMeasure", required = true)
            protected Products.Product.CSItem.UnitOfMeasure unitOfMeasure;

            /**
             * Gets the value of the csValue property.
             * 
             * @return
             *     possible object is
             *     {@link Products.Product.CSItem.CSValue }
             *     
             */
            public Products.Product.CSItem.CSValue getCSValue() {
                return csValue;
            }

            /**
             * Sets the value of the csValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link Products.Product.CSItem.CSValue }
             *     
             */
            public void setCSValue(Products.Product.CSItem.CSValue value) {
                this.csValue = value;
            }

            /**
             * Gets the value of the unitOfMeasure property.
             * 
             * @return
             *     possible object is
             *     {@link Products.Product.CSItem.UnitOfMeasure }
             *     
             */
            public Products.Product.CSItem.UnitOfMeasure getUnitOfMeasure() {
                return unitOfMeasure;
            }

            /**
             * Sets the value of the unitOfMeasure property.
             * 
             * @param value
             *     allowed object is
             *     {@link Products.Product.CSItem.UnitOfMeasure }
             *     
             */
            public void setUnitOfMeasure(Products.Product.CSItem.UnitOfMeasure value) {
                this.unitOfMeasure = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CSValueName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "csValueName"
            })
            public static class CSValue {

                @XmlElement(name = "CSValueName", required = true)
                protected String csValueName;

                /**
                 * Gets the value of the csValueName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCSValueName() {
                    return csValueName;
                }

                /**
                 * Sets the value of the csValueName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCSValueName(String value) {
                    this.csValueName = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="UnitOfMeasureName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="UnitOfMeasureSymbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "unitOfMeasureName",
                "unitOfMeasureSymbol"
            })
            public static class UnitOfMeasure {

                @XmlElement(name = "UnitOfMeasureName", required = true)
                protected String unitOfMeasureName;
                @XmlElement(name = "UnitOfMeasureSymbol", required = true)
                protected String unitOfMeasureSymbol;

                /**
                 * Gets the value of the unitOfMeasureName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUnitOfMeasureName() {
                    return unitOfMeasureName;
                }

                /**
                 * Sets the value of the unitOfMeasureName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUnitOfMeasureName(String value) {
                    this.unitOfMeasureName = value;
                }

                /**
                 * Gets the value of the unitOfMeasureSymbol property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUnitOfMeasureSymbol() {
                    return unitOfMeasureSymbol;
                }

                /**
                 * Sets the value of the unitOfMeasureSymbol property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUnitOfMeasureSymbol(String value) {
                    this.unitOfMeasureSymbol = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="FeatureCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="FeatureReferenceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="FeatureName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="FeatureLongDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="FeatureGlossary" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="FeatureRank" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="FeatureTopRank" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "featureCode",
            "featureReferenceName",
            "featureName",
            "featureLongDescription",
            "featureGlossary",
            "featureRank",
            "featureTopRank"
        })
        public static class Feature {

            @XmlElement(name = "FeatureCode", required = true)
            protected String featureCode;
            @XmlElement(name = "FeatureReferenceName", required = true)
            protected String featureReferenceName;
            @XmlElement(name = "FeatureName", required = true)
            protected String featureName;
            @XmlElement(name = "FeatureLongDescription", required = true)
            protected String featureLongDescription;
            @XmlElement(name = "FeatureGlossary", required = true)
            protected String featureGlossary;
            @XmlElement(name = "FeatureRank")
            protected String featureRank;
            @XmlElement(name = "FeatureTopRank")
            protected String featureTopRank;

            /**
             * Gets the value of the featureCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFeatureCode() {
                return featureCode;
            }

            /**
             * Sets the value of the featureCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFeatureCode(String value) {
                this.featureCode = value;
            }

            /**
             * Gets the value of the featureReferenceName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFeatureReferenceName() {
                return featureReferenceName;
            }

            /**
             * Sets the value of the featureReferenceName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFeatureReferenceName(String value) {
                this.featureReferenceName = value;
            }

            /**
             * Gets the value of the featureName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFeatureName() {
                return featureName;
            }

            /**
             * Sets the value of the featureName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFeatureName(String value) {
                this.featureName = value;
            }

            /**
             * Gets the value of the featureLongDescription property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFeatureLongDescription() {
                return featureLongDescription;
            }

            /**
             * Sets the value of the featureLongDescription property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFeatureLongDescription(String value) {
                this.featureLongDescription = value;
            }

            /**
             * Gets the value of the featureGlossary property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFeatureGlossary() {
                return featureGlossary;
            }

            /**
             * Sets the value of the featureGlossary property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFeatureGlossary(String value) {
                this.featureGlossary = value;
            }

            /**
             * Gets the value of the featureRank property.
             * 
             */
            public String getFeatureRank() {
                return featureRank;
            }

            /**
             * Sets the value of the featureRank property.
             * 
             */
            public void setFeatureRank(String value) {
                this.featureRank = value;
            }

            /**
             * Gets the value of the featureTopRank property.
             * 
             */
            public String getFeatureTopRank() {
                return featureTopRank;
            }

            /**
             * Sets the value of the featureTopRank property.
             * 
             */
            public void setFeatureTopRank(String value) {
                this.featureTopRank = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Family">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="FamilyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Descriptor">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="DescriptorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "family",
            "descriptor"
        })
        public static class NamingString {

            @XmlElement(name = "Family", required = true)
            protected Products.Product.NamingString.Family family;
            @XmlElement(name = "Descriptor", required = true)
            protected Products.Product.NamingString.Descriptor descriptor;

            /**
             * Gets the value of the family property.
             * 
             * @return
             *     possible object is
             *     {@link Products.Product.NamingString.Family }
             *     
             */
            public Products.Product.NamingString.Family getFamily() {
                return family;
            }

            /**
             * Sets the value of the family property.
             * 
             * @param value
             *     allowed object is
             *     {@link Products.Product.NamingString.Family }
             *     
             */
            public void setFamily(Products.Product.NamingString.Family value) {
                this.family = value;
            }

            /**
             * Gets the value of the descriptor property.
             * 
             * @return
             *     possible object is
             *     {@link Products.Product.NamingString.Descriptor }
             *     
             */
            public Products.Product.NamingString.Descriptor getDescriptor() {
                return descriptor;
            }

            /**
             * Sets the value of the descriptor property.
             * 
             * @param value
             *     allowed object is
             *     {@link Products.Product.NamingString.Descriptor }
             *     
             */
            public void setDescriptor(Products.Product.NamingString.Descriptor value) {
                this.descriptor = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="DescriptorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "descriptorName"
            })
            public static class Descriptor {

                @XmlElement(name = "DescriptorName", required = true)
                protected String descriptorName;

                /**
                 * Gets the value of the descriptorName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDescriptorName() {
                    return descriptorName;
                }

                /**
                 * Sets the value of the descriptorName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDescriptorName(String value) {
                    this.descriptorName = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="FamilyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "familyName"
            })
            public static class Family {

                @XmlElement(name = "FamilyName", required = true)
                protected String familyName;

                /**
                 * Gets the value of the familyName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFamilyName() {
                    return familyName;
                }

                /**
                 * Sets the value of the familyName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFamilyName(String value) {
                    this.familyName = value;
                }

            }

        }

    }

}
