#
# ansible-playbook -i localhost-inventory build-step-globals.yml
#
---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
  - account: "{{ lookup('env','AWS_ACCOUNT_NAME') }}"
  - subdomain: "" # subdomain if building non-production (named eg. "staging." with appended dot)
  vars_files:
  - var_files/{{ lookup('env','AWS_ACCOUNT_NAME') }}-account.yml
  - var_files/steppublisher.yml
  tasks:
  - name: Upload cloudformation template to S3
    command: aws s3 cp "{{ lookup('filepath', 'cf/stepglobals.json') }}" s3://{{bucketname}}/ --region "{{region}}"

  - name: Run stepglobals cf template
    cloudformation2:
      stack_name: "StepGlobals"
      state: present
      region: "{{region}}"
      template_url: "https://s3-{{region}}.amazonaws.com/{{bucketname}}/stepglobals.json"
      tags:
        Customer: "Glueteam"
    register: stepglobals
